CREATE TABLE TB_ORDER (
    id SERIAL PRIMARY KEY,
    order_id VARCHAR(50) NOT NULL,
    user_id VARCHAR(50) NOT NULL,
    item_name VARCHAR(100) NOT NULL,
    amount INT NOT NULL,
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);